#!/bin/bash

sxhkd &

if [ -x $HOME/.config/bspwm/dual_mode ]; then
	$HOME/.config/bspwm/./dual_mode
fi

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP2 -d 1

bspc config pointer_mod         mod4
bspc config pointer_action1     move

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp        	desktop='^8' state=floating follow=on
bspc rule -a Zathura     	state=tiled
bspc rule -a Matplotlib  	state=floating
bspc rule -a "GNU Octave"    state=floating
bspc rule -a processing-app-Base    state=floating

$HOME/.config/polybar/launch.sh
