#!/bin/bash

my_laptop_external_monitor=$(xrandr --query | grep 'DP2')
if [[ $my_laptop_external_monitor = *connected* ]]; then
	xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output DP2 --mode 1440x900 --rotate normal --above eDP1
	./.fehbg
fi
